# Config file .travis.yml

language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

env:
    - ODOO="https://github.com/savoirfairelinux/odoo/archive/setuptools-addons.tar.gz"  # Temp until https://github.com/odoo/odoo/issues/185 or https://github.com/odoo/odoo/issues/441 is fixed
#    - ODOO="https://github.com/odoo/odoo/archive/master.tar.gz"

install: 
    - pip install coveralls flake8
    - pip install http://download.gna.org/pychart/PyChart-1.39.tar.gz
    - pip install ${ODOO}

before_script: 
    - createdb test
    - sudo python -m smtpd -n -c DebuggingServer localhost:25 &

# Preload modules before testing to only run tests of repo's modules
# Include current directory and dependent repos in addons-path as well as official addons
script:
    - flake8 . --exclude=__unported__ --filename=__init__.py --ignore=F401
    - flake8 . --exclude=__unported__,__init__.py
    - odoo.py -d test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".") and x != "__unported__"))') --addons-path=$(pwd),`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/addons
    - coverage run $(which odoo.py) -d test --test-enable --log-level=test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".") and x != "__unported__"))') --addons-path=$(pwd),`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/addons

after_success:
  coveralls
