# Config file .travis.yml

language: python

python:
    - "2.7"

virtualenv:
   system_site_packages: true

before_install: 
    - export ODOO_ORG="odoo"
    - export ODOO_BRANCH="master"
    - export ODOO_URL="https://github.com/${ODOO_ORG}/odoo/archive/${ODOO_BRANCH}.tar.gz"
    - export ODOO_CMD="../${ODOO_ORG}-${ODOO_BRANCH}/odoo.py"

install:
    - wget -O odoo.tar.gz ${ODOO_URL}
    - tar -xf odoo.tar.gz -C ../
    - pip install -r requirements.txt

before_script:
    - createdb test

script:
    - flake8 . --max-line-length=120 --exclude=__unported__ --filename=__init__.py --ignore=F401
    - flake8 . --max-line-length=120 --exclude=__unported__,__init__.py
    - ${ODOO_CMD} -d test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".") and x != "__unported__"))') --addons-path=$(pwd),`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/addons
    - coverage run ${ODOO_CMD} -d test --test-enable --log-level=test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".") and x != "__unported__"))') --addons-path=$(pwd),`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/addons

after_success:
    coveralls
